### ISSUE TITLE
Implement direct-to-s3 apis

### ISSUE THREAD

**Issue by Rennzie** [petrbroz/forge-server-utils#40]
Hi @petrbroz , 

Will you be updating this API to include the upcoming changes for `direct-to-s3`? I can see you've made a start in [projects](https://github.com/petrbroz/forge-server-utils/projects/1), but would be keen to learn of any timeline you're working to, if at all?

**Comment by petrbroz** [comment]
Hi @Rennzie, yes, I'm planning to add the direct-to-s3 support. I'm afraid I won't have enough time before Autodesk University, though, so realistically this would be implemented sometime in October or November.

**Comment by Rennzie** [comment]
Ah ok thanks @petrbroz, much appreciated. 

You may know the answer to this, would the old system still work beyond September 30th? The [blog](https://forge.autodesk.com/blog/data-management-oss-object-storage-service-migrating-direct-s3-approach) mentioned deprecation at the end of September but went on to say it wouldn't be usable anymore so we're a little confused on how immediately we need to act.

**Comment by petrbroz** [comment]
I believe the deadline has been moved to the end of the year.

**Comment by petrbroz** [comment]
Btw. version 9.0.0 has just been released, and it includes the new direct-s3 APIs.

**Comment by Rennzie** [comment]
Legend. Thanks @petrbroz!

**Comment by justinmanley** [comment]
hi @petrbroz! thanks for adding support for direct-to-s3 upload!

just to confirm the best path for the direct-to-s3 migration -- we currently use `DataManagementClient.uploadObject` from v8.4.0 of this library. In order to become compliant with the [new direct-to-S3 flow](https://forge.autodesk.com/blog/data-management-oss-object-storage-service-migrating-direct-s3-approach) that will become mandatory at the end of this year, is it sufficient for us to just upgrade the library to v9.0.0? Or do we also need to switch from `DataManagementClient.uploadObject` to some other API in this library?
